name: Soooo
title: Product Desinger Sojung
description: blah blah blah
tags:
  - blog
  - designer
  - product designer
  - UX
  - UI
  - UX designer
  - UXUI designer
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
email: namsojung93@gmail.com
disqus_username: disqus_YvgOPTmYLH
